---
abstract: 'Use the Amazon S3 - Simple Storage Service'
author:
  - 'Pedro Figueiredo <me@pedrofigueiredo.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  LWP::Simple: 0
  Test::Exception: 0
  Test::More: 0
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-S3
requires:
  Carp: 0
  Data::Stream::Bulk::Callback: 0
  DateTime::Format::HTTP: 0
  Digest::HMAC_SHA1: 0
  Digest::MD5: 0
  Digest::MD5::File: 0
  File::Find::Rule: 0
  File::stat: 0
  Getopt::Long: 0
  HTTP::Date: 0
  HTTP::Status: 0
  IO::File: 1.14
  LWP::UserAgent::Determined: 0
  MIME::Base64: 0
  MIME::Types: 0
  Moose: 0.85
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0.16
  MooseX::Types::DateTime::MoreCoercions: 0.07
  Path::Class: 0
  Pod::Usage: 0
  Regexp::Common: 0
  Term::Encoding: 0
  Term::ProgressBar::Simple: 0
  URI: 0
  URI::Escape: 0
  URI::QueryParam: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/pfig/net-amazon-s3/issues
  repository: https://github.com/pfig/net-amazon-s3.git
version: 0.60
